### ISSUE TITLE
Implement generic I*SyncCacheProvider<'T> interfaces

### ISSUE THREAD

**Issue by cmeeren** [App-vNext/Polly.Caching.MemoryCache#24]
`MemoryCacheProvider`  can't be used when specifying e.g. `ResultTtl` as the `ttlStrategy`, because it doesn't implement `ISyncCacheProvider<'T>` and `IAsyncCacheProvider<'T>`. Subclassing `MemoryCacheProvider` and implementing these interfaces should be a trivial addition to this library and would save users from having to do so themselves.

**Comment by reisenberger** [comment]
You should be able to use `MemoryCacheProvider .AsyncFor<TResult>(...)` to make a version of `MemoryCacheProvider` fulfilling (eg) `IAsyncCacheProvider<T>`.  A similar overload exists fro sync.  A previous similar discussion [is here](https://github.com/App-vNext/Polly/issues/461#issuecomment-392754828).  We need to get this into the documentation.

**Comment by cmeeren** [comment]
Great, thanks! This should indeed be documented.

**Comment by reisenberger** [comment]
Added documentation: https://github.com/App-vNext/Polly.Caching.MemoryCache#note
