### ISSUE TITLE
Remove explicit statement of NETStandard.Library 2.0 package dependency

### ISSUE THREAD

**Issue by mbp** [App-vNext/Polly.Caching.MemoryCache#26]
There is a NuGet dependency on `NETStandard.Library  (>= 2.0.0)` in the netstandard2.0 target of this package. I don't believe this is needed or wanted. When I install the package in a project, it also adds this package, but that package is implicitly already there since it is obviously a netstandard2.0 compatible project.

It is also the recommendation here: https://github.com/dotnet/standard/blob/master/docs/faq.md#should-i-reference-the-meta-package-or-should-i-reference-individual-packages

**Comment by reisenberger** [comment]
@mbp Thanks for this.  Agree.  It should be fixed in #29, releasing as Polly.Caching.Memory v2.0.1, in the next few days.
