### ISSUE TITLE
boolean 'false' values are never cached (generalised: default(TResult) for value types)

### ISSUE THREAD

**Issue by cmeeren** [App-vNext/Polly.Caching.MemoryCache#28]
It seems that when a function returns `false`, the value is never cached.

Repro solution: [Repro.zip](https://github.com/App-vNext/Polly.Caching.MemoryCache/files/2514785/Repro.zip)

For quick reference, the code in the repro solution is:

```f#
open System
open Microsoft.Extensions.Caching.Memory
open Polly
open Polly.Caching.Memory

let cachePolicy =
  Policy.Cache(
    MemoryCacheProvider(new MemoryCache(MemoryCacheOptions())),
    TimeSpan.FromMinutes 1.,
    (fun ctx key -> printfn "  GET %s" key),
    (fun ctx key -> printfn "  MISS %s" key),
    (fun ctx key -> printfn "  PUT %s" key),
    (fun ctx key ex -> printfn "  GETERR %s %s" key ex.Message),
    (fun ctx key ex -> printfn "  PUTERR %s %s" key ex.Message)
  )

let getFalseCached () =
  cachePolicy.Execute((fun ctx -> false), Context("key-false"))

let getTrueCached () =
  cachePolicy.Execute((fun ctx -> true), Context("key-true"))

[<EntryPoint>]
let main argv =
  printfn "True:"
  printfn "First call: "
  getTrueCached () |> ignore
  printfn "Second call: "
  getTrueCached () |> ignore

  printfn ""

  printfn "False"
  printfn "First call: "
  getFalseCached () |> ignore
  printfn "Second call: "
  getFalseCached () |> ignore

  Console.ReadLine() |> ignore
  0
```

Expected behavior:

```
True:
First call:
  MISS key-true
  PUT key-true
Second call:
  GET key-true

False
First call:
  MISS key-false
  PUT key-false
Second call:
  GET key-false
```

Actual behavior:

```
True:
First call:
  MISS key-true
  PUT key-true
Second call:
  GET key-true

False
First call:
  MISS key-false
Second call:
  MISS key-false
```

**Comment by reisenberger** [comment]
@cmeeren See the [diagnosis here](https://stackoverflow.com/a/52919523/) and [interim workround here](https://stackoverflow.com/questions/52919181/polly-cache-policy-is-not-adding-values-to-the-cache#comment92768106_52919523).  I'll carry this over to the [main Polly repo](https://github.com/App-vNext/Polly/issues) in due course as the cause is actually in core Polly.

I think this is behaviour we should change/fix.

**Comment by cmeeren** [comment]
Yes, I completely agree that this should be changed. :) Not caching default values for value types caught me completely off-guard, there are probably other places I have to look too. Thanks!

**Comment by cmeeren** [comment]
In fact, I strongly believe the behavior should be changed for reference types, too. `null` is a perfectly valid and cacheable return value (e.g. for database lookups where nothing was found).

This goes doubly for F# where one might use the generic `Option` type to represent a missing value; even though `Option` is a value type, it's implemented in a way that its default value is `None`, and thus any `Option`-wrapped value won't be cached if it is `None`.

**Comment by reisenberger** [comment]
It is possible also that the same breaking-change fixes would be required to fix the value-type `default(TResult)` case - to confirm.
